kind: pipeline
name: default

steps:

- name: test
  image: docker.parasynthetic.dev/karlredman/flask-base:latest
  pull: if-not-exists
  commands:
    # - ./test.sh 3.5.3
    # - ./test.sh 3.6.8
    - ./test.sh 3.7.2

- name: build
  image: docker.parasynthetic.dev/karlredman/flask-base:latest
  pull: if-not-exists
  commands:
    - bash -c 'source /root/.bashrc && ./app.py build'

# - name: install_test
#   image: plugins/pypi
#   commands:
#     - apk add build-base
#     - apk add python3-dev
#     - apk add libffi-dev
#     - apk add openssl-dev
#     - pip3 install -r ./requirements.txt
#     - pip3 install -e .
#     - flake8 .
#     # build target is ./docs/
#     - ./app.py build

- name: deploy
  image: docker:git
  environment:
    # SSH_USER:
    #   from_secret: ssh_user
    SSH_KEY:
      from_secret: ssh_key
    SSH_HOST:
      from_secret: ssh_host
    USER_EMAIL:
      from_secret: user_email
    USER_NAME:
      from_secret: user_name
    TARGET_REPO:
      from_secret: target_repo
  commands:
    - git config --global user.email "$${USER_EMAIL}"
    - git config --global user.name "$${USER_NAME}"
    - ./drone-ssh-helper.sh
